### ISSUE TITLE
Stop using flakehell, switch to wps-light

### ISSUE THREAD

**Issue by pawamoy** [pawamoy/copier-poetry#15]
See commit in mkdocstrings to remove flakehell.
Push wps-light 0.15.2 to pypi, use it in this template.
Move flake8 config to config/flake8.ini (see mkdocstrings again)

**Comment by pawamoy** [comment]
Done.

**Comment by rachmadaniHaryono** [comment]
flakehell is removed but it is still mentioned on readme and docs

**Comment by pawamoy** [comment]
Indeed, thanks. Would you like to contribute and update the docs (I don't use this template anymore)?
